docker_django_project:
    image: fanghao/ubuntu-django:1.0
    container_name: docker_django_project
    restart: always
    volumes:
        - /home/data/docker/docker_django_project/project:/opt/django/project
        - /home/data/docker/docker_django_project/logs:/opt/django/logs
        - /home/data/docker/docker_django_project/venv:/opt/django/venv
        - /home/python/.ssh:/root/.ssh
    dns:
        - 192.168.1.109
    ports:
        - "8000:8000"

