survey:
    image: fanghao/ubuntu-django
    container_name: docker_django_project
    restart: always
    volumes:
        - /home/data/docker/docker_django_project/project:/opt/django/project
        - /home/data/docker/docker_django_project/logs:/opt/django/logs
        - /home/data/docker/docker_django_project/venv:/opt/django/venv
    ports:
        - "8100:8000"

